#include "geometry/EmulsionDetector/DetectorDefinition.hpp"

chamberstructitem chamber_def[] {
    {0, 20000, PLACE_NEXT},      // spring gap
    {"AcBoard5mm", -1, PLACE_NEXT}, // push board

    {"Film", -1, PLACE_NEXT},
    {"G4_Fe", 300, PLACE_NEXT},
    {"UnitFrame", -1, ZCENTER_MATCH}, // unit 130
    {"Film", -1, PLACE_NEXT},
    {/* "G4_WATER"*/ 0, 1500, PLACE_NEXT},  // Using water of mother volume.
    {"WaterFrame", -1, ZCENTER_MATCH},
    {"Film", -1, PLACE_NEXT},
    {"G4_Fe", 300, PLACE_NEXT},
    {"UnitFrame", -1, ZCENTER_MATCH}, // unit 129
    {"Film", -1, PLACE_NEXT},
    {/* "G4_WATER"*/ 0, 1500, PLACE_NEXT},
    {"WaterFrame", -1, ZCENTER_MATCH},
    {"Film", -1, PLACE_NEXT},
    {"G4_Fe", 300, PLACE_NEXT},
    {"UnitFrame", -1, ZCENTER_MATCH}, // unit 128
    {"Film", -1, PLACE_NEXT},
    {/* "G4_WATER"*/ 0, 1500, PLACE_NEXT},
    {"WaterFrame", -1, ZCENTER_MATCH},
    {"Film", -1, PLACE_NEXT},
    {"G4_Fe", 300, PLACE_NEXT},
    {"UnitFrame", -1, ZCENTER_MATCH}, // unit 127
    {"Film", -1, PLACE_NEXT},
    {/* "G4_WATER"*/ 0, 1500, PLACE_NEXT},
    {"WaterFrame", -1, ZCENTER_MATCH},
    {"Film", -1, PLACE_NEXT},
    {"G4_Fe", 300, PLACE_NEXT},
    {"UnitFrame", -1, ZCENTER_MATCH}, // unit 126
    {"Film", -1, PLACE_NEXT},
    {/* "G4_WATER"*/ 0, 1500, PLACE_NEXT},
    {"WaterFrame", -1, ZCENTER_MATCH},
    {"Film", -1, PLACE_NEXT},
    {"G4_Fe", 300, PLACE_NEXT},
    {"UnitFrame", -1, ZCENTER_MATCH}, // unit 125
    {"Film", -1, PLACE_NEXT},
    {/* "G4_WATER"*/ 0, 1500, PLACE_NEXT},
    {"WaterFrame", -1, ZCENTER_MATCH},
    {"Film", -1, PLACE_NEXT},
    {"G4_Fe", 300, PLACE_NEXT},
    {"UnitFrame", -1, ZCENTER_MATCH}, // unit 124
    {"Film", -1, PLACE_NEXT},
    {/* "G4_WATER"*/ 0, 1500, PLACE_NEXT},
    {"WaterFrame", -1, ZCENTER_MATCH},
    {"Film", -1, PLACE_NEXT},
    {"G4_Fe", 300, PLACE_NEXT},
    {"UnitFrame", -1, ZCENTER_MATCH}, // unit 123
    {"Film", -1, PLACE_NEXT},
    {/* "G4_WATER"*/ 0, 1500, PLACE_NEXT},
    {"WaterFrame", -1, ZCENTER_MATCH},
    {"Film", -1, PLACE_NEXT},
    {"G4_Fe", 300, PLACE_NEXT},
    {"UnitFrame", -1, ZCENTER_MATCH}, // unit 122
    {"Film", -1, PLACE_NEXT},
    {/* "G4_WATER"*/ 0, 1500, PLACE_NEXT},
    {"WaterFrame", -1, ZCENTER_MATCH},
    {"Film", -1, PLACE_NEXT},
    {"G4_Fe", 300, PLACE_NEXT},
    {"UnitFrame", -1, ZCENTER_MATCH}, // unit 121
    {"Film", -1, PLACE_NEXT},
    {/* "G4_WATER"*/ 0, 1500, PLACE_NEXT},
    {"WaterFrame", -1, ZCENTER_MATCH},

    {"Film", -1, PLACE_NEXT},
    {"G4_Fe", 300, PLACE_NEXT},
    {"UnitFrame", -1, ZCENTER_MATCH}, // unit 120
    {"Film", -1, PLACE_NEXT},
    {/* "G4_WATER"*/ 0, 1500, PLACE_NEXT},
    {"WaterFrame", -1, ZCENTER_MATCH},
    {"Film", -1, PLACE_NEXT},
    {"G4_Fe", 300, PLACE_NEXT},
    {"UnitFrame", -1, ZCENTER_MATCH},
    {"Film", -1, PLACE_NEXT},
    {/* "G4_WATER"*/ 0, 1500, PLACE_NEXT},
    {"WaterFrame", -1, ZCENTER_MATCH},
    {"Film", -1, PLACE_NEXT},
    {"G4_Fe", 300, PLACE_NEXT},
    {"UnitFrame", -1, ZCENTER_MATCH},
    {"Film", -1, PLACE_NEXT},
    {/* "G4_WATER"*/ 0, 1500, PLACE_NEXT},
    {"WaterFrame", -1, ZCENTER_MATCH},
    {"Film", -1, PLACE_NEXT},
    {"G4_Fe", 300, PLACE_NEXT},
    {"UnitFrame", -1, ZCENTER_MATCH},
    {"Film", -1, PLACE_NEXT},
    {/* "G4_WATER"*/ 0, 1500, PLACE_NEXT},
    {"WaterFrame", -1, ZCENTER_MATCH},
    {"Film", -1, PLACE_NEXT},
    {"G4_Fe", 300, PLACE_NEXT},
    {"UnitFrame", -1, ZCENTER_MATCH},
    {"Film", -1, PLACE_NEXT},
    {/* "G4_WATER"*/ 0, 1500, PLACE_NEXT},
    {"WaterFrame", -1, ZCENTER_MATCH},
    {"Film", -1, PLACE_NEXT},
    {"G4_Fe", 300, PLACE_NEXT},
    {"UnitFrame", -1, ZCENTER_MATCH},
    {"Film", -1, PLACE_NEXT},
    {/* "G4_WATER"*/ 0, 1500, PLACE_NEXT},
    {"WaterFrame", -1, ZCENTER_MATCH},
    {"Film", -1, PLACE_NEXT},
    {"G4_Fe", 300, PLACE_NEXT},
    {"UnitFrame", -1, ZCENTER_MATCH},
    {"Film", -1, PLACE_NEXT},
    {/* "G4_WATER"*/ 0, 1500, PLACE_NEXT},
    {"WaterFrame", -1, ZCENTER_MATCH},
    {"Film", -1, PLACE_NEXT},
    {"G4_Fe", 300, PLACE_NEXT},
    {"UnitFrame", -1, ZCENTER_MATCH},
    {"Film", -1, PLACE_NEXT},
    {/* "G4_WATER"*/ 0, 1500, PLACE_NEXT},
    {"WaterFrame", -1, ZCENTER_MATCH},
    {"Film", -1, PLACE_NEXT},
    {"G4_Fe", 300, PLACE_NEXT},
    {"UnitFrame", -1, ZCENTER_MATCH},
    {"Film", -1, PLACE_NEXT},
    {/* "G4_WATER"*/ 0, 1500, PLACE_NEXT},
    {"WaterFrame", -1, ZCENTER_MATCH},
    {"Film", -1, PLACE_NEXT},
    {"G4_Fe", 300, PLACE_NEXT},
    {"UnitFrame", -1, ZCENTER_MATCH},
    {"Film", -1, PLACE_NEXT},
    {/* "G4_WATER"*/ 0, 1500, PLACE_NEXT},
    {"WaterFrame", -1, ZCENTER_MATCH},

    {"Film", -1, PLACE_NEXT},
    {"G4_Fe", 300, PLACE_NEXT},
    {"UnitFrame", -1, ZCENTER_MATCH}, // unit 110
    {"Film", -1, PLACE_NEXT},
    {/* "G4_WATER"*/ 0, 1500, PLACE_NEXT},
    {"WaterFrame", -1, ZCENTER_MATCH},
    {"Film", -1, PLACE_NEXT},
    {"G4_Fe", 300, PLACE_NEXT},
    {"UnitFrame", -1, ZCENTER_MATCH},
    {"Film", -1, PLACE_NEXT},
    {/* "G4_WATER"*/ 0, 1500, PLACE_NEXT},
    {"WaterFrame", -1, ZCENTER_MATCH},
    {"Film", -1, PLACE_NEXT},
    {"G4_Fe", 300, PLACE_NEXT},
    {"UnitFrame", -1, ZCENTER_MATCH},
    {"Film", -1, PLACE_NEXT},
    {/* "G4_WATER"*/ 0, 1500, PLACE_NEXT},
    {"WaterFrame", -1, ZCENTER_MATCH},
    {"Film", -1, PLACE_NEXT},
    {"G4_Fe", 300, PLACE_NEXT},
    {"UnitFrame", -1, ZCENTER_MATCH},
    {"Film", -1, PLACE_NEXT},
    {/* "G4_WATER"*/ 0, 1500, PLACE_NEXT},
    {"WaterFrame", -1, ZCENTER_MATCH},
    {"Film", -1, PLACE_NEXT},
    {"G4_Fe", 300, PLACE_NEXT},
    {"UnitFrame", -1, ZCENTER_MATCH},
    {"Film", -1, PLACE_NEXT},
    {/* "G4_WATER"*/ 0, 1500, PLACE_NEXT},
    {"WaterFrame", -1, ZCENTER_MATCH},
    {"Film", -1, PLACE_NEXT},
    {"G4_Fe", 300, PLACE_NEXT},
    {"UnitFrame", -1, ZCENTER_MATCH},
    {"Film", -1, PLACE_NEXT},
    {/* "G4_WATER"*/ 0, 1500, PLACE_NEXT},
    {"WaterFrame", -1, ZCENTER_MATCH},
    {"Film", -1, PLACE_NEXT},
    {"G4_Fe", 300, PLACE_NEXT},
    {"UnitFrame", -1, ZCENTER_MATCH},
    {"Film", -1, PLACE_NEXT},
    {/* "G4_WATER"*/ 0, 1500, PLACE_NEXT},
    {"WaterFrame", -1, ZCENTER_MATCH},
    {"Film", -1, PLACE_NEXT},
    {"G4_Fe", 300, PLACE_NEXT},
    {"UnitFrame", -1, ZCENTER_MATCH},
    {"Film", -1, PLACE_NEXT},
    {/* "G4_WATER"*/ 0, 1500, PLACE_NEXT},
    {"WaterFrame", -1, ZCENTER_MATCH},
    {"Film", -1, PLACE_NEXT},
    {"G4_Fe", 300, PLACE_NEXT},
    {"UnitFrame", -1, ZCENTER_MATCH},
    {"Film", -1, PLACE_NEXT},
    {/* "G4_WATER"*/ 0, 1500, PLACE_NEXT},
    {"WaterFrame", -1, ZCENTER_MATCH},
    {"Film", -1, PLACE_NEXT},
    {"G4_Fe", 300, PLACE_NEXT},
    {"UnitFrame", -1, ZCENTER_MATCH},
    {"Film", -1, PLACE_NEXT},
    {/* "G4_WATER"*/ 0, 1500, PLACE_NEXT},
    {"WaterFrame", -1, ZCENTER_MATCH},

    {"Film", -1, PLACE_NEXT},
    {"G4_Fe", 300, PLACE_NEXT},
    {"UnitFrame", -1, ZCENTER_MATCH}, // unit 100
    {"Film", -1, PLACE_NEXT},
    {/* "G4_WATER"*/ 0, 1500, PLACE_NEXT},
    {"WaterFrame", -1, ZCENTER_MATCH},
    {"Film", -1, PLACE_NEXT},
    {"G4_Fe", 300, PLACE_NEXT},
    {"UnitFrame", -1, ZCENTER_MATCH},
    {"Film", -1, PLACE_NEXT},
    {/* "G4_WATER"*/ 0, 1500, PLACE_NEXT},
    {"WaterFrame", -1, ZCENTER_MATCH},
    {"Film", -1, PLACE_NEXT},
    {"G4_Fe", 300, PLACE_NEXT},
    {"UnitFrame", -1, ZCENTER_MATCH},
    {"Film", -1, PLACE_NEXT},
    {/* "G4_WATER"*/ 0, 1500, PLACE_NEXT},
    {"WaterFrame", -1, ZCENTER_MATCH},
    {"Film", -1, PLACE_NEXT},
    {"G4_Fe", 300, PLACE_NEXT},
    {"UnitFrame", -1, ZCENTER_MATCH},
    {"Film", -1, PLACE_NEXT},
    {/* "G4_WATER"*/ 0, 1500, PLACE_NEXT},
    {"WaterFrame", -1, ZCENTER_MATCH},
    {"Film", -1, PLACE_NEXT},
    {"G4_Fe", 300, PLACE_NEXT},
    {"UnitFrame", -1, ZCENTER_MATCH},
    {"Film", -1, PLACE_NEXT},
    {/* "G4_WATER"*/ 0, 1500, PLACE_NEXT},
    {"WaterFrame", -1, ZCENTER_MATCH},
    {"Film", -1, PLACE_NEXT},
    {"G4_Fe", 300, PLACE_NEXT},
    {"UnitFrame", -1, ZCENTER_MATCH},
    {"Film", -1, PLACE_NEXT},
    {/* "G4_WATER"*/ 0, 1500, PLACE_NEXT},
    {"WaterFrame", -1, ZCENTER_MATCH},
    {"Film", -1, PLACE_NEXT},
    {"G4_Fe", 300, PLACE_NEXT},
    {"UnitFrame", -1, ZCENTER_MATCH},
    {"Film", -1, PLACE_NEXT},
    {/* "G4_WATER"*/ 0, 1500, PLACE_NEXT},
    {"WaterFrame", -1, ZCENTER_MATCH},
    {"Film", -1, PLACE_NEXT},
    {"G4_Fe", 300, PLACE_NEXT},
    {"UnitFrame", -1, ZCENTER_MATCH},
    {"Film", -1, PLACE_NEXT},
    {/* "G4_WATER"*/ 0, 1500, PLACE_NEXT},
    {"WaterFrame", -1, ZCENTER_MATCH},
    {"Film", -1, PLACE_NEXT},
    {"G4_Fe", 300, PLACE_NEXT},
    {"UnitFrame", -1, ZCENTER_MATCH},
    {"Film", -1, PLACE_NEXT},
    {/* "G4_WATER"*/ 0, 1500, PLACE_NEXT},
    {"WaterFrame", -1, ZCENTER_MATCH},
    {"Film", -1, PLACE_NEXT},
    {"G4_Fe", 300, PLACE_NEXT},
    {"UnitFrame", -1, ZCENTER_MATCH},
    {"Film", -1, PLACE_NEXT},
    {/* "G4_WATER"*/ 0, 1500, PLACE_NEXT},
    {"WaterFrame", -1, ZCENTER_MATCH},

    {"Film", -1, PLACE_NEXT},
    {"G4_Fe", 300, PLACE_NEXT},
    {"UnitFrame", -1, ZCENTER_MATCH}, // unit 90
    {"Film", -1, PLACE_NEXT},
    {/* "G4_WATER"*/ 0, 1500, PLACE_NEXT},
    {"WaterFrame", -1, ZCENTER_MATCH},
    {"Film", -1, PLACE_NEXT},
    {"G4_Fe", 300, PLACE_NEXT},
    {"UnitFrame", -1, ZCENTER_MATCH},
    {"Film", -1, PLACE_NEXT},
    {/* "G4_WATER"*/ 0, 1500, PLACE_NEXT},
    {"WaterFrame", -1, ZCENTER_MATCH},
    {"Film", -1, PLACE_NEXT},
    {"G4_Fe", 300, PLACE_NEXT},
    {"UnitFrame", -1, ZCENTER_MATCH},
    {"Film", -1, PLACE_NEXT},
    {/* "G4_WATER"*/ 0, 1500, PLACE_NEXT},
    {"WaterFrame", -1, ZCENTER_MATCH},
    {"Film", -1, PLACE_NEXT},
    {"G4_Fe", 300, PLACE_NEXT},
    {"UnitFrame", -1, ZCENTER_MATCH},
    {"Film", -1, PLACE_NEXT},
    {/* "G4_WATER"*/ 0, 1500, PLACE_NEXT},
    {"WaterFrame", -1, ZCENTER_MATCH},
    {"Film", -1, PLACE_NEXT},
    {"G4_Fe", 300, PLACE_NEXT},
    {"UnitFrame", -1, ZCENTER_MATCH},
    {"Film", -1, PLACE_NEXT},
    {/* "G4_WATER"*/ 0, 1500, PLACE_NEXT},
    {"WaterFrame", -1, ZCENTER_MATCH},
    {"Film", -1, PLACE_NEXT},
    {"G4_Fe", 300, PLACE_NEXT},
    {"UnitFrame", -1, ZCENTER_MATCH},
    {"Film", -1, PLACE_NEXT},
    {/* "G4_WATER"*/ 0, 1500, PLACE_NEXT},
    {"WaterFrame", -1, ZCENTER_MATCH},
    {"Film", -1, PLACE_NEXT},
    {"G4_Fe", 300, PLACE_NEXT},
    {"UnitFrame", -1, ZCENTER_MATCH},
    {"Film", -1, PLACE_NEXT},
    {/* "G4_WATER"*/ 0, 1500, PLACE_NEXT},
    {"WaterFrame", -1, ZCENTER_MATCH},
    {"Film", -1, PLACE_NEXT},
    {"G4_Fe", 300, PLACE_NEXT},
    {"UnitFrame", -1, ZCENTER_MATCH},
    {"Film", -1, PLACE_NEXT},
    {/* "G4_WATER"*/ 0, 1500, PLACE_NEXT},
    {"WaterFrame", -1, ZCENTER_MATCH},
    {"Film", -1, PLACE_NEXT},
    {"G4_Fe", 300, PLACE_NEXT},
    {"UnitFrame", -1, ZCENTER_MATCH},
    {"Film", -1, PLACE_NEXT},
    {/* "G4_WATER"*/ 0, 1500, PLACE_NEXT},
    {"WaterFrame", -1, ZCENTER_MATCH},
    {"Film", -1, PLACE_NEXT},
    {"G4_Fe", 300, PLACE_NEXT},
    {"UnitFrame", -1, ZCENTER_MATCH},
    {"Film", -1, PLACE_NEXT},
    {/* "G4_WATER"*/ 0, 1500, PLACE_NEXT},
    {"WaterFrame", -1, ZCENTER_MATCH},

    {"Film", -1, PLACE_NEXT},
    {"G4_Fe", 300, PLACE_NEXT},
    {"UnitFrame", -1, ZCENTER_MATCH}, // unit 80
    {"Film", -1, PLACE_NEXT},
    {/* "G4_WATER"*/ 0, 1500, PLACE_NEXT},
    {"WaterFrame", -1, ZCENTER_MATCH},
    {"Film", -1, PLACE_NEXT},
    {"G4_Fe", 300, PLACE_NEXT},
    {"UnitFrame", -1, ZCENTER_MATCH},
    {"Film", -1, PLACE_NEXT},
    {/* "G4_WATER"*/ 0, 1500, PLACE_NEXT},
    {"WaterFrame", -1, ZCENTER_MATCH},
    {"Film", -1, PLACE_NEXT},
    {"G4_Fe", 300, PLACE_NEXT},
    {"UnitFrame", -1, ZCENTER_MATCH},
    {"Film", -1, PLACE_NEXT},
    {/* "G4_WATER"*/ 0, 1500, PLACE_NEXT},
    {"WaterFrame", -1, ZCENTER_MATCH},
    {"Film", -1, PLACE_NEXT},
    {"G4_Fe", 300, PLACE_NEXT},
    {"UnitFrame", -1, ZCENTER_MATCH},
    {"Film", -1, PLACE_NEXT},
    {/* "G4_WATER"*/ 0, 1500, PLACE_NEXT},
    {"WaterFrame", -1, ZCENTER_MATCH},
    {"Film", -1, PLACE_NEXT},
    {"G4_Fe", 300, PLACE_NEXT},
    {"UnitFrame", -1, ZCENTER_MATCH},
    {"Film", -1, PLACE_NEXT},
    {/* "G4_WATER"*/ 0, 1500, PLACE_NEXT},
    {"WaterFrame", -1, ZCENTER_MATCH},
    {"Film", -1, PLACE_NEXT},
    {"G4_Fe", 300, PLACE_NEXT},
    {"UnitFrame", -1, ZCENTER_MATCH},
    {"Film", -1, PLACE_NEXT},
    {/* "G4_WATER"*/ 0, 1500, PLACE_NEXT},
    {"WaterFrame", -1, ZCENTER_MATCH},
    {"Film", -1, PLACE_NEXT},
    {"G4_Fe", 300, PLACE_NEXT},
    {"UnitFrame", -1, ZCENTER_MATCH},
    {"Film", -1, PLACE_NEXT},
    {/* "G4_WATER"*/ 0, 1500, PLACE_NEXT},
    {"WaterFrame", -1, ZCENTER_MATCH},
    {"Film", -1, PLACE_NEXT},
    {"G4_Fe", 300, PLACE_NEXT},
    {"UnitFrame", -1, ZCENTER_MATCH},
    {"Film", -1, PLACE_NEXT},
    {/* "G4_WATER"*/ 0, 1500, PLACE_NEXT},
    {"WaterFrame", -1, ZCENTER_MATCH},
    {"Film", -1, PLACE_NEXT},
    {"G4_Fe", 300, PLACE_NEXT},
    {"UnitFrame", -1, ZCENTER_MATCH},
    {"Film", -1, PLACE_NEXT},
    {/* "G4_WATER"*/ 0, 1500, PLACE_NEXT},
    {"WaterFrame", -1, ZCENTER_MATCH},
    {"Film", -1, PLACE_NEXT},
    {"G4_Fe", 300, PLACE_NEXT},
    {"UnitFrame", -1, ZCENTER_MATCH},
    {"Film", -1, PLACE_NEXT},
    {/* "G4_WATER"*/ 0, 1500, PLACE_NEXT},
    {"WaterFrame", -1, ZCENTER_MATCH},

    {"Film", -1, PLACE_NEXT},
    {"G4_Fe", 300, PLACE_NEXT},
    {"UnitFrame", -1, ZCENTER_MATCH}, // unit 70
    {"Film", -1, PLACE_NEXT},
    {/* "G4_WATER"*/ 0, 1500, PLACE_NEXT},
    {"WaterFrame", -1, ZCENTER_MATCH},
    {"Film", -1, PLACE_NEXT},
    {"G4_Fe", 300, PLACE_NEXT},
    {"UnitFrame", -1, ZCENTER_MATCH},
    {"Film", -1, PLACE_NEXT},
    {/* "G4_WATER"*/ 0, 1500, PLACE_NEXT},
    {"WaterFrame", -1, ZCENTER_MATCH},
    {"Film", -1, PLACE_NEXT},
    {"G4_Fe", 300, PLACE_NEXT},
    {"UnitFrame", -1, ZCENTER_MATCH},
    {"Film", -1, PLACE_NEXT},
    {/* "G4_WATER"*/ 0, 1500, PLACE_NEXT},
    {"WaterFrame", -1, ZCENTER_MATCH},
    {"Film", -1, PLACE_NEXT},
    {"G4_Fe", 300, PLACE_NEXT},
    {"UnitFrame", -1, ZCENTER_MATCH},
    {"Film", -1, PLACE_NEXT},
    {/* "G4_WATER"*/ 0, 1500, PLACE_NEXT},
    {"WaterFrame", -1, ZCENTER_MATCH},
    {"Film", -1, PLACE_NEXT},
    {"G4_Fe", 300, PLACE_NEXT},
    {"UnitFrame", -1, ZCENTER_MATCH},
    {"Film", -1, PLACE_NEXT},
    {/* "G4_WATER"*/ 0, 1500, PLACE_NEXT},
    {"WaterFrame", -1, ZCENTER_MATCH},
    {"Film", -1, PLACE_NEXT},
    {"G4_Fe", 300, PLACE_NEXT},
    {"UnitFrame", -1, ZCENTER_MATCH},
    {"Film", -1, PLACE_NEXT},
    {/* "G4_WATER"*/ 0, 1500, PLACE_NEXT},
    {"WaterFrame", -1, ZCENTER_MATCH},
    {"Film", -1, PLACE_NEXT},
    {"G4_Fe", 300, PLACE_NEXT},
    {"UnitFrame", -1, ZCENTER_MATCH},
    {"Film", -1, PLACE_NEXT},
    {/* "G4_WATER"*/ 0, 1500, PLACE_NEXT},
    {"WaterFrame", -1, ZCENTER_MATCH},
    {"Film", -1, PLACE_NEXT},
    {"G4_Fe", 300, PLACE_NEXT},
    {"UnitFrame", -1, ZCENTER_MATCH},
    {"Film", -1, PLACE_NEXT},
    {/* "G4_WATER"*/ 0, 1500, PLACE_NEXT},
    {"WaterFrame", -1, ZCENTER_MATCH},
    {"Film", -1, PLACE_NEXT},
    {"G4_Fe", 300, PLACE_NEXT},
    {"UnitFrame", -1, ZCENTER_MATCH},
    {"Film", -1, PLACE_NEXT},
    {/* "G4_WATER"*/ 0, 1500, PLACE_NEXT},
    {"WaterFrame", -1, ZCENTER_MATCH},
    {"Film", -1, PLACE_NEXT},
    {"G4_Fe", 300, PLACE_NEXT},
    {"UnitFrame", -1, ZCENTER_MATCH},
    {"Film", -1, PLACE_NEXT},
    {/* "G4_WATER"*/ 0, 1500, PLACE_NEXT},
    {"WaterFrame", -1, ZCENTER_MATCH},

    {"Film", -1, PLACE_NEXT},
    {"G4_Fe", 300, PLACE_NEXT},
    {"UnitFrame", -1, ZCENTER_MATCH}, // unit 60
    {"Film", -1, PLACE_NEXT},
    {/* "G4_WATER"*/ 0, 1500, PLACE_NEXT},
    {"WaterFrame", -1, ZCENTER_MATCH},
    {"Film", -1, PLACE_NEXT},
    {"G4_Fe", 300, PLACE_NEXT},
    {"UnitFrame", -1, ZCENTER_MATCH},
    {"Film", -1, PLACE_NEXT},
    {/* "G4_WATER"*/ 0, 1500, PLACE_NEXT},
    {"WaterFrame", -1, ZCENTER_MATCH},
    {"Film", -1, PLACE_NEXT},
    {"G4_Fe", 300, PLACE_NEXT},
    {"UnitFrame", -1, ZCENTER_MATCH},
    {"Film", -1, PLACE_NEXT},
    {/* "G4_WATER"*/ 0, 1500, PLACE_NEXT},
    {"WaterFrame", -1, ZCENTER_MATCH},
    {"Film", -1, PLACE_NEXT},
    {"G4_Fe", 300, PLACE_NEXT},
    {"UnitFrame", -1, ZCENTER_MATCH},
    {"Film", -1, PLACE_NEXT},
    {/* "G4_WATER"*/ 0, 1500, PLACE_NEXT},
    {"WaterFrame", -1, ZCENTER_MATCH},
    {"Film", -1, PLACE_NEXT},
    {"G4_Fe", 300, PLACE_NEXT},
    {"UnitFrame", -1, ZCENTER_MATCH},
    {"Film", -1, PLACE_NEXT},
    {/* "G4_WATER"*/ 0, 1500, PLACE_NEXT},
    {"WaterFrame", -1, ZCENTER_MATCH},
    {"Film", -1, PLACE_NEXT},
    {"G4_Fe", 300, PLACE_NEXT},
    {"UnitFrame", -1, ZCENTER_MATCH},
    {"Film", -1, PLACE_NEXT},
    {/* "G4_WATER"*/ 0, 1500, PLACE_NEXT},
    {"WaterFrame", -1, ZCENTER_MATCH},
    {"Film", -1, PLACE_NEXT},
    {"G4_Fe", 300, PLACE_NEXT},
    {"UnitFrame", -1, ZCENTER_MATCH},
    {"Film", -1, PLACE_NEXT},
    {/* "G4_WATER"*/ 0, 1500, PLACE_NEXT},
    {"WaterFrame", -1, ZCENTER_MATCH},
    {"Film", -1, PLACE_NEXT},
    {"G4_Fe", 300, PLACE_NEXT},
    {"UnitFrame", -1, ZCENTER_MATCH},
    {"Film", -1, PLACE_NEXT},
    {/* "G4_WATER"*/ 0, 1500, PLACE_NEXT},
    {"WaterFrame", -1, ZCENTER_MATCH},
    {"Film", -1, PLACE_NEXT},
    {"G4_Fe", 300, PLACE_NEXT},
    {"UnitFrame", -1, ZCENTER_MATCH},
    {"Film", -1, PLACE_NEXT},
    {/* "G4_WATER"*/ 0, 1500, PLACE_NEXT},
    {"WaterFrame", -1, ZCENTER_MATCH},
    {"Film", -1, PLACE_NEXT},
    {"G4_Fe", 300, PLACE_NEXT},
    {"UnitFrame", -1, ZCENTER_MATCH},
    {"Film", -1, PLACE_NEXT},
    {/* "G4_WATER"*/ 0, 1500, PLACE_NEXT},
    {"WaterFrame", -1, ZCENTER_MATCH},

    {"Film", -1, PLACE_NEXT},
    {"G4_Fe", 300, PLACE_NEXT},
    {"UnitFrame", -1, ZCENTER_MATCH}, // unit 50
    {"Film", -1, PLACE_NEXT},
    {/* "G4_WATER"*/ 0, 1500, PLACE_NEXT},
    {"WaterFrame", -1, ZCENTER_MATCH},
    {"Film", -1, PLACE_NEXT},
    {"G4_Fe", 300, PLACE_NEXT},
    {"UnitFrame", -1, ZCENTER_MATCH},
    {"Film", -1, PLACE_NEXT},
    {/* "G4_WATER"*/ 0, 1500, PLACE_NEXT},
    {"WaterFrame", -1, ZCENTER_MATCH},
    {"Film", -1, PLACE_NEXT},
    {"G4_Fe", 300, PLACE_NEXT},
    {"UnitFrame", -1, ZCENTER_MATCH},
    {"Film", -1, PLACE_NEXT},
    {/* "G4_WATER"*/ 0, 1500, PLACE_NEXT},
    {"WaterFrame", -1, ZCENTER_MATCH},
    {"Film", -1, PLACE_NEXT},
    {"G4_Fe", 300, PLACE_NEXT},
    {"UnitFrame", -1, ZCENTER_MATCH},
    {"Film", -1, PLACE_NEXT},
    {/* "G4_WATER"*/ 0, 1500, PLACE_NEXT},
    {"WaterFrame", -1, ZCENTER_MATCH},
    {"Film", -1, PLACE_NEXT},
    {"G4_Fe", 300, PLACE_NEXT},
    {"UnitFrame", -1, ZCENTER_MATCH},
    {"Film", -1, PLACE_NEXT},
    {/* "G4_WATER"*/ 0, 1500, PLACE_NEXT},
    {"WaterFrame", -1, ZCENTER_MATCH},
    {"Film", -1, PLACE_NEXT},
    {"G4_Fe", 300, PLACE_NEXT},
    {"UnitFrame", -1, ZCENTER_MATCH},
    {"Film", -1, PLACE_NEXT},
    {/* "G4_WATER"*/ 0, 1500, PLACE_NEXT},
    {"WaterFrame", -1, ZCENTER_MATCH},
    {"Film", -1, PLACE_NEXT},
    {"G4_Fe", 300, PLACE_NEXT},
    {"UnitFrame", -1, ZCENTER_MATCH},
    {"Film", -1, PLACE_NEXT},
    {/* "G4_WATER"*/ 0, 1500, PLACE_NEXT},
    {"WaterFrame", -1, ZCENTER_MATCH},
    {"Film", -1, PLACE_NEXT},
    {"G4_Fe", 300, PLACE_NEXT},
    {"UnitFrame", -1, ZCENTER_MATCH},
    {"Film", -1, PLACE_NEXT},
    {/* "G4_WATER"*/ 0, 1500, PLACE_NEXT},
    {"WaterFrame", -1, ZCENTER_MATCH},
    {"Film", -1, PLACE_NEXT},
    {"G4_Fe", 300, PLACE_NEXT},
    {"UnitFrame", -1, ZCENTER_MATCH},
    {"Film", -1, PLACE_NEXT},
    {/* "G4_WATER"*/ 0, 1500, PLACE_NEXT},
    {"WaterFrame", -1, ZCENTER_MATCH},
    {"Film", -1, PLACE_NEXT},
    {"G4_Fe", 300, PLACE_NEXT},
    {"UnitFrame", -1, ZCENTER_MATCH},
    {"Film", -1, PLACE_NEXT},
    {/* "G4_WATER"*/ 0, 1500, PLACE_NEXT},
    {"WaterFrame", -1, ZCENTER_MATCH},

    {"Film", -1, PLACE_NEXT},
    {"G4_Fe", 300, PLACE_NEXT},
    {"UnitFrame", -1, ZCENTER_MATCH}, // unit 40
    {"Film", -1, PLACE_NEXT},
    {/* "G4_WATER"*/ 0, 1500, PLACE_NEXT},
    {"WaterFrame", -1, ZCENTER_MATCH},
    {"Film", -1, PLACE_NEXT},
    {"G4_Fe", 300, PLACE_NEXT},
    {"UnitFrame", -1, ZCENTER_MATCH},
    {"Film", -1, PLACE_NEXT},
    {/* "G4_WATER"*/ 0, 1500, PLACE_NEXT},
    {"WaterFrame", -1, ZCENTER_MATCH},
    {"Film", -1, PLACE_NEXT},
    {"G4_Fe", 300, PLACE_NEXT},
    {"UnitFrame", -1, ZCENTER_MATCH},
    {"Film", -1, PLACE_NEXT},
    {/* "G4_WATER"*/ 0, 1500, PLACE_NEXT},
    {"WaterFrame", -1, ZCENTER_MATCH},
    {"Film", -1, PLACE_NEXT},
    {"G4_Fe", 300, PLACE_NEXT},
    {"UnitFrame", -1, ZCENTER_MATCH},
    {"Film", -1, PLACE_NEXT},
    {/* "G4_WATER"*/ 0, 1500, PLACE_NEXT},
    {"WaterFrame", -1, ZCENTER_MATCH},
    {"Film", -1, PLACE_NEXT},
    {"G4_Fe", 300, PLACE_NEXT},
    {"UnitFrame", -1, ZCENTER_MATCH},
    {"Film", -1, PLACE_NEXT},
    {/* "G4_WATER"*/ 0, 1500, PLACE_NEXT},
    {"WaterFrame", -1, ZCENTER_MATCH},
    {"Film", -1, PLACE_NEXT},
    {"G4_Fe", 300, PLACE_NEXT},
    {"UnitFrame", -1, ZCENTER_MATCH},
    {"Film", -1, PLACE_NEXT},
    {/* "G4_WATER"*/ 0, 1500, PLACE_NEXT},
    {"WaterFrame", -1, ZCENTER_MATCH},
    {"Film", -1, PLACE_NEXT},
    {"G4_Fe", 300, PLACE_NEXT},
    {"UnitFrame", -1, ZCENTER_MATCH},
    {"Film", -1, PLACE_NEXT},
    {/* "G4_WATER"*/ 0, 1500, PLACE_NEXT},
    {"WaterFrame", -1, ZCENTER_MATCH},
    {"Film", -1, PLACE_NEXT},
    {"G4_Fe", 300, PLACE_NEXT},
    {"UnitFrame", -1, ZCENTER_MATCH},
    {"Film", -1, PLACE_NEXT},
    {/* "G4_WATER"*/ 0, 1500, PLACE_NEXT},
    {"WaterFrame", -1, ZCENTER_MATCH},
    {"Film", -1, PLACE_NEXT},
    {"G4_Fe", 300, PLACE_NEXT},
    {"UnitFrame", -1, ZCENTER_MATCH},
    {"Film", -1, PLACE_NEXT},
    {/* "G4_WATER"*/ 0, 1500, PLACE_NEXT},
    {"WaterFrame", -1, ZCENTER_MATCH},
    {"Film", -1, PLACE_NEXT},
    {"G4_Fe", 300, PLACE_NEXT},
    {"UnitFrame", -1, ZCENTER_MATCH},
    {"Film", -1, PLACE_NEXT},
    {/* "G4_WATER"*/ 0, 1500, PLACE_NEXT},
    {"WaterFrame", -1, ZCENTER_MATCH},

    {"Film", -1, PLACE_NEXT},
    {"G4_Fe", 300, PLACE_NEXT},
    {"UnitFrame", -1, ZCENTER_MATCH}, // unit 30
    {"Film", -1, PLACE_NEXT},
    {/* "G4_WATER"*/ 0, 1500, PLACE_NEXT},
    {"WaterFrame", -1, ZCENTER_MATCH},
    {"Film", -1, PLACE_NEXT},
    {"G4_Fe", 300, PLACE_NEXT},
    {"UnitFrame", -1, ZCENTER_MATCH},
    {"Film", -1, PLACE_NEXT},
    {/* "G4_WATER"*/ 0, 1500, PLACE_NEXT},
    {"WaterFrame", -1, ZCENTER_MATCH},
    {"Film", -1, PLACE_NEXT},
    {"G4_Fe", 300, PLACE_NEXT},
    {"UnitFrame", -1, ZCENTER_MATCH},
    {"Film", -1, PLACE_NEXT},
    {/* "G4_WATER"*/ 0, 1500, PLACE_NEXT},
    {"WaterFrame", -1, ZCENTER_MATCH},
    {"Film", -1, PLACE_NEXT},
    {"G4_Fe", 300, PLACE_NEXT},
    {"UnitFrame", -1, ZCENTER_MATCH},
    {"Film", -1, PLACE_NEXT},
    {/* "G4_WATER"*/ 0, 1500, PLACE_NEXT},
    {"WaterFrame", -1, ZCENTER_MATCH},
    {"Film", -1, PLACE_NEXT},
    {"G4_Fe", 300, PLACE_NEXT},
    {"UnitFrame", -1, ZCENTER_MATCH},
    {"Film", -1, PLACE_NEXT},
    {/* "G4_WATER"*/ 0, 1500, PLACE_NEXT},
    {"WaterFrame", -1, ZCENTER_MATCH},
    {"Film", -1, PLACE_NEXT},
    {"G4_Fe", 300, PLACE_NEXT},
    {"UnitFrame", -1, ZCENTER_MATCH},
    {"Film", -1, PLACE_NEXT},
    {/* "G4_WATER"*/ 0, 1500, PLACE_NEXT},
    {"WaterFrame", -1, ZCENTER_MATCH},
    {"Film", -1, PLACE_NEXT},
    {"G4_Fe", 300, PLACE_NEXT},
    {"UnitFrame", -1, ZCENTER_MATCH},
    {"Film", -1, PLACE_NEXT},
    {/* "G4_WATER"*/ 0, 1500, PLACE_NEXT},
    {"WaterFrame", -1, ZCENTER_MATCH},
    {"Film", -1, PLACE_NEXT},
    {"G4_Fe", 300, PLACE_NEXT},
    {"UnitFrame", -1, ZCENTER_MATCH},
    {"Film", -1, PLACE_NEXT},
    {/* "G4_WATER"*/ 0, 1500, PLACE_NEXT},
    {"WaterFrame", -1, ZCENTER_MATCH},
    {"Film", -1, PLACE_NEXT},
    {"G4_Fe", 300, PLACE_NEXT},
    {"UnitFrame", -1, ZCENTER_MATCH},
    {"Film", -1, PLACE_NEXT},
    {/* "G4_WATER"*/ 0, 1500, PLACE_NEXT},
    {"WaterFrame", -1, ZCENTER_MATCH},
    {"Film", -1, PLACE_NEXT},
    {"G4_Fe", 300, PLACE_NEXT},
    {"UnitFrame", -1, ZCENTER_MATCH},
    {"Film", -1, PLACE_NEXT},
    {/* "G4_WATER"*/ 0, 1500, PLACE_NEXT},
    {"WaterFrame", -1, ZCENTER_MATCH},

    {"Film", -1, PLACE_NEXT},
    {"G4_Fe", 300, PLACE_NEXT},
    {"UnitFrame", -1, ZCENTER_MATCH}, // unit 20
    {"Film", -1, PLACE_NEXT},
    {/* "G4_WATER"*/ 0, 1500, PLACE_NEXT},
    {"WaterFrame", -1, ZCENTER_MATCH},
    {"Film", -1, PLACE_NEXT},
    {"G4_Fe", 300, PLACE_NEXT},
    {"UnitFrame", -1, ZCENTER_MATCH},
    {"Film", -1, PLACE_NEXT},
    {/* "G4_WATER"*/ 0, 1500, PLACE_NEXT},
    {"WaterFrame", -1, ZCENTER_MATCH},
    {"Film", -1, PLACE_NEXT},
    {"G4_Fe", 300, PLACE_NEXT},
    {"UnitFrame", -1, ZCENTER_MATCH},
    {"Film", -1, PLACE_NEXT},
    {/* "G4_WATER"*/ 0, 1500, PLACE_NEXT},
    {"WaterFrame", -1, ZCENTER_MATCH},
    {"Film", -1, PLACE_NEXT},
    {"G4_Fe", 300, PLACE_NEXT},
    {"UnitFrame", -1, ZCENTER_MATCH},
    {"Film", -1, PLACE_NEXT},
    {/* "G4_WATER"*/ 0, 1500, PLACE_NEXT},
    {"WaterFrame", -1, ZCENTER_MATCH},
    {"Film", -1, PLACE_NEXT},
    {"G4_Fe", 300, PLACE_NEXT},
    {"UnitFrame", -1, ZCENTER_MATCH},
    {"Film", -1, PLACE_NEXT},
    {/* "G4_WATER"*/ 0, 1500, PLACE_NEXT},
    {"WaterFrame", -1, ZCENTER_MATCH},
    {"Film", -1, PLACE_NEXT},
    {"G4_Fe", 300, PLACE_NEXT},
    {"UnitFrame", -1, ZCENTER_MATCH},
    {"Film", -1, PLACE_NEXT},
    {/* "G4_WATER"*/ 0, 1500, PLACE_NEXT},
    {"WaterFrame", -1, ZCENTER_MATCH},
    {"Film", -1, PLACE_NEXT},
    {"G4_Fe", 300, PLACE_NEXT},
    {"UnitFrame", -1, ZCENTER_MATCH},
    {"Film", -1, PLACE_NEXT},
    {/* "G4_WATER"*/ 0, 1500, PLACE_NEXT},
    {"WaterFrame", -1, ZCENTER_MATCH},
    {"Film", -1, PLACE_NEXT},
    {"G4_Fe", 300, PLACE_NEXT},
    {"UnitFrame", -1, ZCENTER_MATCH},
    {"Film", -1, PLACE_NEXT},
    {/* "G4_WATER"*/ 0, 1500, PLACE_NEXT},
    {"WaterFrame", -1, ZCENTER_MATCH},
    {"Film", -1, PLACE_NEXT},
    {"G4_Fe", 300, PLACE_NEXT},
    {"UnitFrame", -1, ZCENTER_MATCH},
    {"Film", -1, PLACE_NEXT},
    {/* "G4_WATER"*/ 0, 1500, PLACE_NEXT},
    {"WaterFrame", -1, ZCENTER_MATCH},
    {"Film", -1, PLACE_NEXT},
    {"G4_Fe", 300, PLACE_NEXT},
    {"UnitFrame", -1, ZCENTER_MATCH},
    {"Film", -1, PLACE_NEXT},
    {/* "G4_WATER"*/ 0, 1500, PLACE_NEXT},
    {"WaterFrame", -1, ZCENTER_MATCH},

    {"Film", -1, PLACE_NEXT},
    {"G4_Fe", 300, PLACE_NEXT},
    {"UnitFrame", -1, ZCENTER_MATCH}, // unit 10
    {"Film", -1, PLACE_NEXT},
    {/* "G4_WATER"*/ 0, 1500, PLACE_NEXT},
    {"WaterFrame", -1, ZCENTER_MATCH},
    {"Film", -1, PLACE_NEXT},
    {"G4_Fe", 300, PLACE_NEXT},
    {"UnitFrame", -1, ZCENTER_MATCH},
    {"Film", -1, PLACE_NEXT},
    {/* "G4_WATER"*/ 0, 1500, PLACE_NEXT},
    {"WaterFrame", -1, ZCENTER_MATCH},
    {"Film", -1, PLACE_NEXT},
    {"G4_Fe", 300, PLACE_NEXT},
    {"UnitFrame", -1, ZCENTER_MATCH},
    {"Film", -1, PLACE_NEXT},
    {/* "G4_WATER"*/ 0, 1500, PLACE_NEXT},
    {"WaterFrame", -1, ZCENTER_MATCH},
    {"Film", -1, PLACE_NEXT},
    {"G4_Fe", 300, PLACE_NEXT},
    {"UnitFrame", -1, ZCENTER_MATCH},
    {"Film", -1, PLACE_NEXT},
    {/* "G4_WATER"*/ 0, 1500, PLACE_NEXT},
    {"WaterFrame", -1, ZCENTER_MATCH},
    {"Film", -1, PLACE_NEXT},
    {"G4_Fe", 300, PLACE_NEXT},
    {"UnitFrame", -1, ZCENTER_MATCH},
    {"Film", -1, PLACE_NEXT},
    {/* "G4_WATER"*/ 0, 1500, PLACE_NEXT},
    {"WaterFrame", -1, ZCENTER_MATCH},
    {"Film", -1, PLACE_NEXT},
    {"G4_Fe", 300, PLACE_NEXT},
    {"UnitFrame", -1, ZCENTER_MATCH},
    {"Film", -1, PLACE_NEXT},
    {/* "G4_WATER"*/ 0, 1500, PLACE_NEXT},
    {"WaterFrame", -1, ZCENTER_MATCH},
    {"Film", -1, PLACE_NEXT},
    {"G4_Fe", 300, PLACE_NEXT},
    {"UnitFrame", -1, ZCENTER_MATCH},
    {"Film", -1, PLACE_NEXT},
    {/* "G4_WATER"*/ 0, 1500, PLACE_NEXT},
    {"WaterFrame", -1, ZCENTER_MATCH},
    {"Film", -1, PLACE_NEXT},
    {"G4_Fe", 300, PLACE_NEXT},
    {"UnitFrame", -1, ZCENTER_MATCH},
    {"Film", -1, PLACE_NEXT},
    {/* "G4_WATER"*/ 0, 1500, PLACE_NEXT},
    {"WaterFrame", -1, ZCENTER_MATCH},
    {"Film", -1, PLACE_NEXT},
    {"G4_Fe", 300, PLACE_NEXT},
    {"UnitFrame", -1, ZCENTER_MATCH}, // unit 2
    {"Film", -1, PLACE_NEXT},
    {/* "G4_WATER"*/ 0, 1500, PLACE_NEXT},
    {"WaterFrame", -1, ZCENTER_MATCH},
    {"Film", -1, PLACE_NEXT},
    {"G4_Fe", 300, PLACE_NEXT},
    {"UnitFrame", -1, ZCENTER_MATCH}, // unit 1
    {"Film", -1, PLACE_NEXT},
	
    {"Film", -1, PLACE_NEXT},
    {"FeECCFrame", -1, ZTOP_MATCH},
    {"G4_Fe", 300, PLACE_NEXT},
    {"Film", -1, PLACE_NEXT},
    {"G4_Fe", 300, PLACE_NEXT},
    {"Film", -1, PLACE_NEXT},
    {"G4_Fe", 300, PLACE_NEXT},
    {"Film", -1, PLACE_NEXT},
    {"G4_Fe", 300, PLACE_NEXT},
    {"Film", -1, PLACE_NEXT},
    {"G4_Fe", 300, PLACE_NEXT},
    {"Film", -1, PLACE_NEXT},
    {"G4_Fe", 300, PLACE_NEXT},
    {"Film", -1, PLACE_NEXT},
    {"G4_Fe", 300, PLACE_NEXT},
    {"Film", -1, PLACE_NEXT},
    {"G4_Fe", 300, PLACE_NEXT},
    {"Film", -1, PLACE_NEXT},
    {"G4_Fe", 300, PLACE_NEXT},
    {"Film", -1, PLACE_NEXT},
    {"G4_Fe", 300, PLACE_NEXT},
    {"Film", -1, PLACE_NEXT},
    {"G4_Fe", 300, PLACE_NEXT},
    {"Film", -1, PLACE_NEXT},
    {"Film", -1, PLACE_NEXT},
    {"PMMA", 2000, PLACE_NEXT},
    {"Film", -1, PLACE_NEXT},
    {"Film", -1, PLACE_NEXT},

    {0, 0, ZPOS_NONE}			// END mark (vacuum with zero thickness)
};

